demo/src/main/java/com/lqdd/demo/framework/domain/BaseEntity.java
package com.lqdd.demo.framework.domain;

import java.io.Serializable;


public abstract class BaseEntity implements Serializable {

	private static final long serialVersionUID = -8774370128378359009L;


	private Long id;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

}

demo/src/main/java/com/lqdd/demo/security/domain/Resource.java
package com.lqdd.demo.security.domain;

import java.util.List;

import javax.faces.context.FacesContext;
import javax.validation.constraints.NotNull;

import org.apache.commons.lang3.StringUtils;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotBlank;

import com.lqdd.demo.common.utils.EnumUtil;
import com.lqdd.demo.framework.domain.AuditableEntity;

public class Resource extends AuditableEntity {

	private static final long serialVersionUID = 8032268871677473656L;

	public static enum Type {
		MENU, BUTTON;

		private final String name;

		private Type() {
			this.name = EnumUtil.getMessage(this, "messages");
		}

		public String getName() {
			return name;
		}
	}

	// 父节点id
	@Length(max = 32)
	private Long parentId;

	// 资源编码
	@NotBlank
	@Length(max = 32)
	private String code;

	// 资源名称
	@NotBlank
	@Length(max = 64)
	private String name;

	// 资源类型 M:菜单 B:按钮
	private Type type = Type.MENU;

	// URL 请求链接
	@Length(max = 512)
	private String url;

	// 排序
	private Integer seq;

	// 权限
	private String permission;

	// 图标
	@Length(max = 32)
	private String icon;

	// 可使用
	@NotNull
	private boolean enable = true;

	// 是否叶子节点
	@NotNull
	private boolean leaf;

	// 描述
	@Length(max = 512)
	private String description;

	// 子资源
	private List<Resource> children;

	public Long getParentId() {
		return parentId;
	}

	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Type getType() {
		return type;
	}

	public void setType(Type type) {
		this.type = type;
	}

	public String getUrl() {
		if (StringUtils.isBlank(this.url)) {
			return "";
		}
		return url;
	}

	public String getOpenUrl() {
		FacesContext context = FacesContext.getCurrentInstance();
		if (context != null) {
			return context.getExternalContext().getRequestContextPath() + url;
		}
		return "";
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Integer getSeq() {
		return seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	public String getPermission() {
		return permission;
	}

	public void setPermission(String permission) {
		this.permission = permission;
	}

	public String getIcon() {
		return icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public boolean isEnable() {
		return enable;
	}

	public void setEnable(boolean enable) {
		this.enable = enable;
	}

	public boolean isLeaf() {
		if (children == null)
			return true;

		return children.isEmpty();
	}

	public void setLeaf(boolean leaf) {
		this.leaf = leaf;
	}

	public List<Resource> getChildren() {
		return children;
	}

	public void setChildren(List<Resource> children) {
		this.children = children;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
}

demo/src/main/java/com/lqdd/demo/common/component/ImplDisposableBean.java
package com.lqdd.demo.common.component;

import org.apache.logging.log4j.LogManager;
import org.springframework.beans.factory.DisposableBean;
import org.springframework.boot.ExitCodeGenerator;
import org.springframework.stereotype.Component;

@Component
public class ImplDisposableBean implements DisposableBean, ExitCodeGenerator {
	@Override
	public void destroy() throws Exception {
		LogManager.shutdown();
	}

	@Override
	public int getExitCode() {
		return 0;
	}
}

demo/src/main/java/com/lqdd/demo/framework/web/faces/controller/FacesController.java
package com.lqdd.demo.framework.web.faces.controller;

import java.io.IOException;
import java.util.Locale;

import javax.faces.FacesException;
import javax.faces.application.FacesMessage;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.beans.factory.NoSuchBeanDefinitionException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.context.MessageSource;
import org.springframework.web.jsf.FacesContextUtils;

import com.lqdd.demo.framework.web.faces.scope.ViewScope;

public abstract class FacesController {

	public static final Logger logger = LogManager.getLogger(FacesController.class);

	@Autowired
	private ViewScope viewScope;
	@Autowired
	private MessageSource messageSource;

	public void onEntry() {
		logger.info("------ enter FacesController");
	}

	public static FacesController getCurrentInstance() {
		FacesContext facesContext = FacesContext.getCurrentInstance();
		String path = facesContext.getExternalContext().getRequestServletPath();
		ApplicationContext applicationContext = FacesContextUtils.getRequiredWebApplicationContext(facesContext);
		try {
			return (FacesController) applicationContext.getBean(path, FacesController.class);
		} catch (NoSuchBeanDefinitionException e) {
		}
		return null;
	}

	public void putViewScope(String name, Object obj) {
		this.viewScope.put(name, obj);
	}

	public Object getViewScope(String name) {
		return this.viewScope.get(name);
	}

	public HttpServletRequest getRequest() {
		return (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
	}

	public HttpServletResponse getResponse() {
		return (HttpServletResponse) FacesContext.getCurrentInstance().getExternalContext().getResponse();
	}

	public void redirectInternal(String url) {
		ExternalContext externalContext = FacesContext.getCurrentInstance().getExternalContext();
		redirectExternal(externalContext.getRequestContextPath() + url);
	}

	public void redirectExternal(String url) {
		ExternalContext externalContext = FacesContext.getCurrentInstance().getExternalContext();
		try {
			externalContext.redirect(url);
		} catch (IOException e) {
			throw new FacesException(e);
		}
	}

	public Locale getLocale() {
		return getResponse().getLocale();
	}

	public String getMessage(String code, Object[] args) {
		return this.messageSource.getMessage(code, args, getLocale());
	}

	public String getMessage(String code, Object[] args, String defaultMessage) {
		return this.messageSource.getMessage(code, args, defaultMessage, getLocale());
	}

	protected void throwValidatorMessages(String code, Object[] args, FacesMessage.Severity severity) {
		FacesMessage facesMessage = new FacesMessage(getMessage(code, args));
		facesMessage.setSeverity(severity);
		FacesContext.getCurrentInstance().addMessage(null, facesMessage);
	}
}

demo/src/main/java/com/lqdd/demo/framework/web/faces/controller/IndexController.java
package com.lqdd.demo.framework.web.faces.controller;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.primefaces.event.TabCloseEvent;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;

import com.lqdd.demo.security.domain.Resource;
import com.lqdd.demo.security.domain.Resource.Type;
import com.lqdd.demo.security.service.ResourceService;

@Controller("/index.faces")
public class IndexController extends FacesController {

	@Autowired
	private ResourceService resourceService;

	@Override
	public void onEntry() {
		putViewScope("activeIndex", 0);
		putViewScope("resources", findMenu());
		putViewScope("selectedResources", new ArrayList<Resource>());
	}

	private List<Resource> findMenu() {
		Map<String, Object> sreachParam = new HashMap<>();
		sreachParam.put("type", Type.MENU);
		return resourceService.findInfo(sreachParam);
	}

	@SuppressWarnings("unchecked")
	public void addTabs(Resource resource) {
		ArrayList<Resource> selectedResources = (ArrayList<Resource>) getViewScope("selectedResources");
		int activeIndex = 0;
		if (!selectedResources.contains(resource)) {
			selectedResources.add(resource);
			activeIndex = selectedResources.size() - 1;
		} else {
			activeIndex = selectedResources.indexOf(resource);
		}
		putViewScope("activeIndex", activeIndex);
	}

	@SuppressWarnings("unchecked")
	public void onTabClose(TabCloseEvent event) {
		ArrayList<Resource> selectedResources = (ArrayList<Resource>) getViewScope("selectedResources");
		selectedResources.remove(event.getData());
	}
}

demo/src/main/java/com/lqdd/demo/framework/web/faces/controller/LoginController.java
package com.lqdd.demo.framework.web.faces.controller;

import javax.faces.application.FacesMessage;

import org.apache.shiro.SecurityUtils;
import org.apache.shiro.authc.IncorrectCredentialsException;
import org.apache.shiro.authc.LockedAccountException;
import org.apache.shiro.authc.UnknownAccountException;
import org.apache.shiro.authc.UsernamePasswordToken;
import org.apache.shiro.subject.Subject;
import org.springframework.stereotype.Controller;

@Controller("/login.faces")
public class LoginController extends FacesController {

	@Override
	public void onEntry() {
		Subject subject = SecurityUtils.getSubject();
		if (subject.isAuthenticated()) {
			redirectInternal("/index.faces");
		}
	}

	public void onLogin() {
		String username = (String) getViewScope("username");
		String password = (String) getViewScope("password");
		Boolean rememberMe = (Boolean) getViewScope("rememberMe");
		Subject subject = SecurityUtils.getSubject();
		UsernamePasswordToken token = new UsernamePasswordToken(username, password, rememberMe);
		try {
			subject.login(token);
			if (subject.isAuthenticated()) {
				redirectInternal("/index.faces");
			}
		} catch (UnknownAccountException ex) {
			throwValidatorMessages("error.usernameError", null, FacesMessage.SEVERITY_ERROR);
		} catch (IncorrectCredentialsException ex) {
			throwValidatorMessages("error.usernameOrPasswordError", null, FacesMessage.SEVERITY_ERROR);
		} catch (LockedAccountException ex) {
			throwValidatorMessages("error.contactTheAdministrator", null, FacesMessage.SEVERITY_ERROR);
		} catch (Exception ex) {
			throwValidatorMessages("error.contactTheAdministrator", null, FacesMessage.SEVERITY_ERROR);
		} finally {
			token.clear();
		}
	}
}

demo/src/main/java/com/lqdd/demo/security/web/faces/controller/ResourceController.java
package com.lqdd.demo.security.web.faces.controller;

import org.primefaces.model.DefaultTreeNode;
import org.primefaces.model.TreeNode;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;

import com.lqdd.demo.framework.web.faces.annotation.MessageRequired;
import com.lqdd.demo.framework.web.faces.annotation.MessageType;
import com.lqdd.demo.framework.web.faces.controller.FacesController;
import com.lqdd.demo.security.domain.Resource;
import com.lqdd.demo.security.service.ResourceService;

@Controller("/views/security/resource.faces")
public class ResourceController extends FacesController {

	@Autowired
	private ResourceService resourceService;

	@Override
	public void onEntry() {
		putViewScope("types", Resource.Type.values());
		find();
	}

	private void find() {
		putViewScope("resources", resourceService.findTree());
		putViewScope("selectedResources", new TreeNode[0]);
	}

	public void add() {
		Resource parentResource = selectedOneResource();
		Resource resource = new Resource();
		if (parentResource != null) {
			resource.setParentId(parentResource.getId());
		}
		putViewScope("parentResource", parentResource);
		putViewScope("resource", resource);
	}

	@MessageRequired(type = MessageType.SAVE)
	public void save() {
		Resource resource = (Resource) getViewScope("resource");
		resourceService.save(resource);
		find();
	}

	public void edit() {
		Resource resource = selectedOneResource();
		Resource parentResource = resourceService.findById(resource.getParentId());
		putViewScope("resource", resource);
		putViewScope("parentResource", parentResource);
	}

	@MessageRequired(type = MessageType.DELETE)
	public void delete() {
		TreeNode[] nodes = (TreeNode[]) getViewScope("selectedResources");
		Resource[] resources = new Resource[nodes.length];
		for (int i = 0; i < nodes.length; i++) {
			resources[i] = (Resource) nodes[i].getData();
		}
		resourceService.delete(resources);
		find();
	}

	private Resource selectedOneResource() {
		TreeNode[] nodes = (TreeNode[]) getViewScope("selectedResources");
		if (nodes != null) {
			TreeNode node = nodes.length > 0 ? nodes[0] : new DefaultTreeNode();
			return (Resource) node.getData();
		}
		return null;
	}
}

demo/src/main/java/com/lqdd/demo/security/web/faces/controller/RoleController.java
package com.lqdd.demo.security.web.faces.controller;

import org.primefaces.event.SelectEvent;
import org.primefaces.model.LazyDataModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;

import com.lqdd.demo.framework.web.faces.annotation.MessageRequired;
import com.lqdd.demo.framework.web.faces.annotation.MessageType;
import com.lqdd.demo.framework.web.faces.controller.FacesController;
import com.lqdd.demo.security.domain.Role;
import com.lqdd.demo.security.service.ResourceService;
import com.lqdd.demo.security.service.RoleService;
import com.lqdd.demo.security.web.model.RoleDataModel;

@Controller("/views/security/role.faces")
public class RoleController extends FacesController {

	@Autowired
	private RoleService roleService;

	@Autowired
	private ResourceService resourceService;

	@Override
	public void onEntry() {
		putViewScope("resources", resourceService.findTree());
		find();
	}

	public LazyDataModel<Role> getDataModel() {
		RoleDataModel dataModel = RoleDataModel.getInstance();
		return dataModel;
	}

	private void find() {
		putViewScope("selectedRole", new Role());
		putViewScope("selectedRoles", new Role[0]);
	}

	public void add() {
		putViewScope("role", new Role());
	}

	@MessageRequired(type = MessageType.SAVE)
	public void save() {
		Role role = (Role) getViewScope("role");
		roleService.save(role);
	}

	public void edit() {
		Role[] roles = (Role[]) getViewScope("selectedRoles");
		Role role = roles.length > 0 ? roles[0] : null;
		putViewScope("role", role);
	}

	@MessageRequired(type = MessageType.DELETE)
	public void delete() {
		Role[] roles = (Role[]) getViewScope("selectedRoles");
		roleService.delete(roles);
	}

	public void onRowSelect(SelectEvent event) {
		Role role = (Role) event.getObject();
		putViewScope("resources", resourceService.findSeleciontTree(role.getResourceIds()));
		putViewScope("selectedRole", role);
	}

	@MessageRequired(type = MessageType.OPERATION)
	public void onClickUpdateResource() {
		Role role = (Role) getViewScope("selectedRole");
		roleService.updateResourceRelation(role);
		putViewScope("resources", resourceService.findSeleciontTree(role.getResourceIds()));
	}
}

demo/src/main/java/com/lqdd/demo/security/web/faces/controller/UserController.java
package com.lqdd.demo.security.web.faces.controller;

import org.apache.shiro.authz.annotation.RequiresPermissions;
import org.primefaces.event.SelectEvent;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;

import com.lqdd.demo.framework.web.faces.annotation.MessageRequired;
import com.lqdd.demo.framework.web.faces.annotation.MessageType;
import com.lqdd.demo.framework.web.faces.controller.FacesController;
import com.lqdd.demo.security.domain.User;
import com.lqdd.demo.security.service.RoleService;
import com.lqdd.demo.security.service.UserService;

@Controller("/views/security/user.faces")
public class UserController extends FacesController {

	@Autowired
	private UserService userService;

	@Autowired
	private RoleService roleService;

	@Override
	public void onEntry() {
		putViewScope("roles", roleService.findTree());
		find();
	}

	@RequiresPermissions(value = { "security/user:view" })
	public void find() {
		putViewScope("selectedUser", new User());
		putViewScope("users", userService.findAll(null));
	}

	public void add() {
		User user = new User();
		putViewScope("user", user);
	}

	@MessageRequired(type = MessageType.SAVE)
	public void save() {
		User user = (User) getViewScope("user");
		userService.save(user);
		find();
	}

	public void edit() {
		User user = (User) getViewScope("selectedUser");
		putViewScope("user", user);
	}

	@MessageRequired(type = MessageType.DELETE)
	public void delete() {
		User user = (User) getViewScope("selectedUser");
		userService.delete(new User[] { user });
		find();
	}

	public void onRowSelect(SelectEvent event) {
		User user = (User) event.getObject();
		user = userService.findById(user.getId());
		putViewScope("roles", roleService.findSeleciontTree(user.getRoleIds()));
	}

}

demo/src/main/webapp/404.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<f:facet name="first">
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<meta name="viewport"
			content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
		<meta name="apple-mobile-web-app-capable" content="yes" />
	</f:facet>
	<title>PrimeFaces Omega</title>
</h:head>

<h:body styleClass="exception-body">
	<div class="exception-wrapper notfound">
		<p:graphicImage name="images/404.png" library="omega-layout" />

		<p class="message-title">Page Not Found!</p>
		<p class="message-summary">The resource you are looking for does
			not exist.</p>

		<p:link>
			<i class="fa fa-home"></i>
			<span>Dashboard</span>
		</p:link>

		<div class="login-footer">PrimeFaces Omega</div>
	</div>

	<h:outputStylesheet name="css/layout.css" library="omega-layout" />
</h:body>

</html>

demo/src/main/webapp/access.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <h:head>
        <f:facet name="first">
            <meta http-equiv="X-UA-Compatible" content="IE=edge" />
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
            <meta name="apple-mobile-web-app-capable" content="yes" />
        </f:facet>
        <title>PrimeFaces Omega</title>
    </h:head>

    <h:body styleClass="exception-body">
        <div class="exception-wrapper access">
            <p:graphicImage name="images/access.png" library="omega-layout" />
            
            <p class="message-title">Access Denied!</p>
            <p class="message-summary">Please contact system administrator</p>
            
            <p:link outcome="dashboard">
                <i class="fa fa-home"></i>
                <span>Dashboard</span>
            </p:link>
            
            <div class="login-footer">PrimeFaces Omega</div>
        </div>
        
        <h:outputStylesheet name="css/layout.css" library="omega-layout" />
    </h:body>

</html>

demo/src/main/webapp/empty.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/template.xhtml">

    <ui:define name="content">
        <div class="ui-g">
            <div class="ui-g-12">
                <div class="card">
                    <h1>Empty Page</h1>
                    <p>Use this page to start from scratch and place your custom content.</p>
                    <p:button outcome="dashboard" value="Home" style="display:inline-block;margin-top:5px"/>
                </div>
            </div>
        </div>
        
    </ui:define>

</ui:composition>

demo/src/main/webapp/error.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <h:head>
        <f:facet name="first">
            <meta http-equiv="X-UA-Compatible" content="IE=edge" />
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
            <meta name="apple-mobile-web-app-capable" content="yes" />
        </f:facet>
        <title>PrimeFaces Omega</title>
    </h:head>

    <h:body styleClass="exception-body">
        <div class="exception-wrapper error">
            <p:graphicImage name="images/error.png" library="omega-layout" />
            
            <p class="message-title">Exception Occured!</p>
            <p class="message-summary">Please contact system administrator</p>
            
            <p:link outcome="dashboard">
                <i class="fa fa-home"></i>
                <span>Dashboard</span>
            </p:link>
            
            <div class="login-footer">PrimeFaces Omega</div>
        </div>
        
        <h:outputStylesheet name="css/layout.css" library="omega-layout" />
    </h:body>

</html>

demo/src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" template="/WEB-INF/template.xhtml">
	<ui:define name="title">
		PMS
	</ui:define>
	<ui:define name="head">
		<h:outputStylesheet>
        	.ui-tabs .ui-tabs-panel{
			    padding: 0px !important; 
        	}
        	#tab .ui-tabs-panels, #tab .ui-tabs-panel{
        		height: 97% ;
        	}
        	#tab .ui-state-active{
	        	box-shadow: 0px -3px 0px 0px #2399e5 inset;
        	}
        	.ui-panel-content {
			    padding: 0px !important;
			    height: 100%;
			}
        </h:outputStylesheet>
	</ui:define>
	<ui:define name="main">
		<h:body>
			<p:tabView id="tab" styleClass="conentTeb" scrollable="true"
				style="height:100%" activeIndex="#{viewScope.activeIndex}">
				<p:ajax event="tabClose" listener="#{controller.onTabClose}" />
				<c:forEach items="#{viewScope.selectedResources}" var="tab"
					varStatus="status">
					<p:tab id="id_#{status.index}" title="#{tab.name}" closable="true">
						<p:panel style="height:100%">
							<iframe src="#{tab.openUrl}" frameborder="0" height="100%"
								width="100%" />
						</p:panel>
					</p:tab>
				</c:forEach>
			</p:tabView>
		</h:body>
	</ui:define>
</ui:composition>

demo/src/main/webapp/login.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<f:facet name="first">
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<meta name="viewport"
			content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
		<meta name="apple-mobile-web-app-capable" content="yes" />
	</f:facet>
	<title>PrimeFaces Omega</title>
	<h:outputScript>
		$(function(){
			
		})
	</h:outputScript>
</h:head>

<h:body styleClass="login-body">
	<h:form id="loginForm" prependId="false">
		<div id="login-wrapper">
			<p:graphicImage name="images/login-logo.png" library="omega-layout" />
			<p:messages id="messages" closable="true" autoUpdate="true" />
			<div id="login-container">
				<span class="title">#{msg['common']['PMS']}</span>
				<div class="ui-g ui-fluid">
					<div class="ui-g-12">
						<p:inputText id="username" label="#{msg['common']['username']}"
							value="#{viewScope.username}"
							placeholder="#{msg['common']['username']}" required="true" />
					</div>
					<div class="ui-g-12">
						<p:password id="password" label="#{msg['common']['password']}"
							value="#{viewScope.password}"
							placeholder="#{msg['common']['password']}" required="true"
							feedback="false" />
					</div>
					<div class="ui-g-12 ui-md-6">
						<span class="remember-me">#{msg['common']['rememberMe']}</span>
						<p:selectBooleanCheckbox id="rememberMe"
							value="#{viewScope.rememberMe}" />
					</div>
					<div class="ui-g-12 ui-md-6">
						<p:link>#{msg['common']['forgotPassword']}</p:link>
					</div>
					<div class="ui-g-12">
						<p:commandButton value="#{msg['common']['login']}"
							icon="fa fa-check" update=":messages"
							action="#{controller.onLogin}" />
					</div>
				</div>
			</div>
			<div class="login-footer">PrimeFaces Omega</div>
		</div>

		<h:outputStylesheet name="css/layout.css" library="omega-layout" />
	</h:form>
</h:body>

</html>